### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by lloricode** [comment]
please add php8.3 on github workflow action, thank you

**Review by lloricode — CHANGES_REQUESTED** [review]
please add php8.3, thank you

**Comment by lloricode** [comment]
Hi, this is error upon visiting site

PHP 8.3.1
Laravel 11.x-dev

`Symfony\ Component \ ErrorHandler \ Error \ FatalError`

```
Declaration of Inspector\Laravel\Middleware\WebRequestMonitoring::terminate($request, $response) must be compatible with Symfony\Component\HttpKernel\TerminableInterface::terminate(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response): void
```

**Comment by ilvalerione** [comment]
> Hi, this is error upon visiting site
> 
> PHP 8.3.1 Laravel 11.x-dev
> 
> `Symfony\ Component \ ErrorHandler \ Error \ FatalError`
> 
> ```
> Declaration of Inspector\Laravel\Middleware\WebRequestMonitoring::terminate($request, $response) must be compatible with Symfony\Component\HttpKernel\TerminableInterface::terminate(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response): void
> ```

That's why this pull request was not merged.

**Pull request closed without merging**
